### ISSUE TITLE
Need a proper README

### ISSUE THREAD

**Issue by jessej-samuel** [jessej-samuel/spotipy#1]

**Comment by ishaanbedi** [comment]
Can you assign it to me?

**Comment by jessej-samuel** [comment]
Sure 👍

**Comment by ishaanbedi** [comment]
Alright! Can you provide me few keywords about the app so that I can make a well-structured Readme file?

**Comment by jessej-samuel** [comment]
Clean UI, localised music, download music. hosted 24x7 , no lag

Made with:
   - "react": "^17.0.2",
   - "react-redux": "^7.2.6",
   - "redux": "^4.1.2"
(It would be nice if you could add these as badges)

Features to be added:
Sort music, search, Spotify link, discord presence

Header:
![header_ss](https://user-images.githubusercontent.com/72020411/148175452-bd3b7c9b-b66b-40df-9535-d4da3d4ff4db.png)
 
 If you need any more info, feel free to ask!

**Comment by ishaanbedi** [comment]
Hi! I have raised a pull request with the updated file. 
Kindly see

**Comment by jessej-samuel** [comment]
Thanks, @ishaanbedi ! Keep up the good work!

**Comment by ishaanbedi** [comment]
@jessej-samuel Thank you! Looking forward to contributing more to the app...
