### ISSUE TITLE
change position of seek bar

### ISSUE THREAD

**Issue by VenomFate-619** [jessej-samuel/spotipy#7]
Position of seek bar needs to change because in many systems moving the cursor to the bottom brings the dock due to which it is not possible to click on seek bar.

**Comment by jessej-samuel** [comment]
> Position of seek bar needs to change because in many systems moving the cursor to the bottom brings the dock due to which it is not possible to click on seek bar.

Ye makes sense. You can move it above the player controls. That should fix the issue ryt?

**Comment by jessej-samuel** [comment]
Issue resolved in commit fe346642fbdeb28dfdfacd056d20b30464d120ac
